language: php

php:
  - nightly

before_script:
  - |
    # not all dependencies advertise PHP 8 support yet
    composer config platform.php 7.4.0
  - composer install --ignore-platform-reqs

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/php-coveralls -v
